project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Learning Diary"
  author: "Xianchen Wang"
  date: now
  chapters:
    - index.qmd
    - Week_2.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  reader-mode: true

bibliography: references.bib

format:
  html:
    theme:
      light: [cosmo, flatly]
      dark: [cosmo, darkly]
    code-link: true
    
  pdf:
    documentclass: scrreprt

editor: visual

