project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Learning Diary"
  author: "Xianchen Wang"
  date: now
  chapters:
    - index.qmd
    - Week_1.qmd
    - Week_2.qmd
    - Week_3.qmd
    - Week_4.qmd
    - Week_5.qmd
    - Week_6.qmd
    - references.qmd
  reader-mode: true

csl: harvard-cite-them-right.csl
bibliography: CASA0023_Learning_Diary.bib

format:
  html:
    theme:
      light: [cosmo, flatly]
      dark: [cosmo, darkly]
    code-link: true
    
  pdf:
    documentclass: scrreprt

editor: visual

